
CREATE TABLE EMP (
  EMPNO INT PRIMARY KEY,
  ENAME VARCHAR(50),
  JOB VARCHAR(50),
  MGR INT,
  HIREDATE DATE,
  SAL INT,
  COMM INT,
  DEPTNO INT
);

CREATE TABLE DEPT (
  DEPTNO INT PRIMARY KEY,
  DNAME VARCHAR(50),
  LOC VARCHAR(50)
);

ALTER TABLE EMP ADD FOREIGN KEY (MGR) REFERENCES EMP(EMPNO);

INSERT INTO EMP (EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES 
(7369, 'SMITH', 'CLERK', 7902, TO_DATE('17-DEC-80', 'DD-MON-YY'), 800, NULL, 20),
(7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('20-FEV-81', 'DD-MON-YY'), 1600, 300, 30),
(7521, 'WARD', 'SALESMAN', 7698, TO_DATE('22-FEV-81', 'DD-MON-YY'), 1250, 500, 30),
(7566, 'JONES', 'MANAGER', 7839, TO_DATE('02-AVR-81', 'DD-MON-YY'), 2975, NULL, 20),
(7654, 'MARTIN', 'SALESMAN', 7698, TO_DATE('28-SEP-81', 'DD-MON-YY'), 1250, 1400, 30),
(7698, 'BLAKE', 'MANAGER', 7839, TO_DATE('01-MAI-81', 'DD-MON-YY'), 2850, NULL, 30),
(7782, 'CLARK', 'MANAGER', 7839, TO_DATE('09-JUI-81', 'DD-MON-YY'), 2450, NULL, 10),
(7788, 'SCOTT', 'ANALYST', 7566, TO_DATE('09-DEC-82', 'DD-MON-YY'), 3000, NULL, 20),
(7839, 'KING', 'PRESIDENT', NULL, TO_DATE('17-NOV-81', 'DD-MON-YY'), 5000, NULL, 10),
(7844, 'TURNER', 'SALESMAN', 7698, TO_DATE('08-SEP-81', 'DD-MON-YY'), 1500, 0, 30),
(7876, 'ADAMS', 'CLERK', 7788, TO_DATE('12-JAN-83', 'DD-MON-YY'), 1100, NULL, 20),
(7900, 'JAMES', 'CLERK', 7698, TO_DATE('03-DEC-81', 'DD-MON-YY'), 950, NULL, 30),
(7902, 'FORD', 'ANALYST', 7566, TO_DATE('03-DEC-81', 'DD-MON-YY'), 3000, NULL, 20),
(7934, 'MILLER', 'CLERK', 7782, TO_DATE('23-JAN-82', 'DD-MON-YY'), 1300, NULL, 10);


SELECT ENAME, JOB, EMPNO, SAL
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB = 'MANAGER' AND SAL > 2800;

SELECT ENAME, JOB
FROM EMP
WHERE JOB = 'MANAGER' AND DEPTNO != 30;

SELECT *
FROM EMP
WHERE SAL BETWEEN 1200 AND 1400;

SELECT ENAME, DEPTNO
FROM EMP
WHERE DEPTNO IN (10,30)
ORDER BY ENAME;

SELECT *
FROM EMP
WHERE DEPTNO = 30
ORDER BY SAL ASC;

SELECT *
FROM EMP
ORDER BY JOB, SAL DESC;

SELECT DISTINCT JOB
FROM EMP;

SELECT DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'ALLEN');

SELECT DNAME, ENAME, JOB, SAL
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
ORDER BY DNAME, SAL DESC;

SELECT ENAME, SAL, COMM, SAL+COMM AS TOTAL_SALARY
FROM EMP
WHERE JOB = 'SALESMAN';

SELECT ENAME, JOB, 'VEN ' || TO_CHAR(HIREDATE, 'DD MON YYYY') AS "DATE D'EMBAUCHE"
FROM EMP
WHERE DEPTNO = 20;

SELECT DEPTNO, MAX(SAL) AS MAX_SALARY
FROM EMP
JOIN dep ON emp.deptno = dept.deptno
GROUP BY DEPTNO;

SELECT DEPTNO, COUNT(*) AS EMP_COUNT,
        SUM(SAL) AS TOTAL_SALARY,
        AVG(SAL) AS AVG_SALARY, JOB
FROM EMP
GROUP BY DEPTNO, JOB;

SELECT DEPTNO, COUNT() AS EMP_COUNT,
SUM(SAL) AS TOTAL_SALARY,
AVG(SAL) AS AVG_SALARY, JOB
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT() >= 2)
GROUP BY DEPTNO, JOB;

SELECT EMP.ENAME, DEPT.DNAME, EMP.SAL
FROM EMP
JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
WHERE EMP.JOB = (SELECT JOB FROM EMP WHERE ENAME = 'JONES');

SELECT ENAME, SAL , JOB,(SELECT AVG(SAL) FROM emp) AS 'Salaire moyenne'
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP);

CREATE TABLE PROJET (
  num_projet INT PRIMARY KEY,
  nom_projet VARCHAR(5),
  budget INTEGER
);

INSERT INTO PROJET (num_projet, nom_projet, budget)
VALUES (101, 'ALPHA', 96000),
       (102, 'BETA', 82000),
       (103, 'GAMMA', 15000);



ALTER TABLE EMP ADD  num_projet INTEGER(3);

UPDATE EMP SET num_projet = 
  CASE 
    WHEN deptno = 30 THEN 101
    ELSE 102
  END;


CREATE VIEW emp_details AS 
SELECT e.ename, e.job, d.dname, p.nom_projet
FROM EMP e 
JOIN DEPT d ON e.deptno = d.deptno 
JOIN PROJET p ON e.num_projet = p.num_projet;

SELECT ename, job, dname, nom_projet 
FROM emp_details 
ORDER BY dname, nom_projet;


SELECT m.ename AS manager_name, p.nom_projet AS project_name
FROM EMP m 
JOIN EMP e ON m.empno = e.mgr 
JOIN PROJET p ON e.num_projet = p.num_projet;

/*partie 2*/

SELECT DISTINCT manager
FROM emp
WHERE deptno IN (20, 30);

SELECT *
FROM emp
WHERE job NOT LIKE '%MANAGER%' AND hiredate BETWEEN '01-JAN-81' AND '31-DEC-81';

SELECT *
FROM emp
WHERE comm IS NOT NULL;

SELECT ename, deptno, job, hiredate
FROM emp
ORDER BY deptno, job, hiredate DESC;

SELECT *
FROM emp
WHERE loc = 'DALLAS';

SELECT e.ename, e.hiredate, m.ename
       AS manager_name, m.hiredate AS manager_hiredate
FROM emp e, emp m
WHERE e.mgr = m.empno AND e.hiredate < m.hiredate;

SELECT emp.ENAME , emp.mgr
FROM emp
WHERE empno NOT IN (SELECT DISTINCT  mgr FROM emp WHERE mgr IS NOT NULL );


SELECT e.ENAME, e.HIREDATE
FROM emp e , emp m
WHERE e.HIREDATE < m.HIREDATE AND m.ENAME ='blake'

SELECT e.ename, e.JOB , e.HIREDATE
FROM emp e
WHERE hiredate = (SELECT hiredate FROM emp WHERE ename = 'FORD');

SELECT ename , job , mgr
FROM emp 
WHERE deptno = (SELECT deptno FROM emp WHERE ename = 'CLARK') AND ename <> 'CLARK' AND mgr IS NOT NULL 

SELECT *
FROM emp
WHERE job = 'SALESMAN' AND mgr = (SELECT mgr FROM emp WHERE ename = 'TURNER');

SELECT r.ename
FROM emp r, emp s
WHERE r.hiredate = s.hiredate AND r.deptno = 'RESEARCH' AND s.deptno = 'SALES';




SELECT ename, DATE_FORMAT (hiredate, '%a') AS day_of_week
FROM emp;

SELECT ename, ROUND((MONTHS_BETWEEN(sysdate, hiredate)/12), 2) AS months_employed
FROM emp;



SELECT ename
FROM emp
WHERE ename LIKE '%M%A%';

SELECT ename
FROM emp
WHERE ename LIKE '%A%A%';

SELECT *
FROM emp
WHERE hiredate < ALL (SELECT hiredate FROM emp WHERE deptno = 10);

SELECT job
FROM emp
GROUP BY job
HAVING AVG(sal) = (SELECT MIN(AVG(sal)) FROM emp GROUP BY job);

SELECT deptno, COUNT(*) AS num
FROM emp
GROUP BY deptno
ORDER BY num DESC LIMIT 1;


SELECT deptno, ROUND((COUNT()/(SELECT COUNT() FROM emp)*100), 2) AS percentage_of_total_employees
FROM emp
GROUP BY deptno;














